apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: onges-users
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=mssql;Database=ONGES-Users;User Id=sa;Password=Senha#123;TrustServerCertificate=True;"
  MongoSettings__ConnectionString: "mongodb://mongo:27017"
  Jwt__Key: "9y4XJg0aTphzFJw3TvksRvqHXd+Q4VB8f7ZvU08N+9Q="
  SA_PASSWORD: "Senha#123"
