apiVersion: v1
kind: Service
metadata:
  name: onges-users-api
  namespace: onges-users
spec:
  type: LoadBalancer
  selector:
    app: onges-users-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: onges-users
spec:
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: onges-users
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
